SecondHandClothes/Controllers/CartController.cs
namespace SecondHandClothes.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using SecondHandClothes.Infrastructure;
    using SecondHandClothes.Services.Cart;

    using static WebConstants;

    public class CartController : Controller
    {
        private readonly ICartService cartService;

        public CartController(ICartService cartService)
        {
            this.cartService = cartService;
        }

        [Authorize]
        public IActionResult MyCart(string userId)
        {
            if (this.User.Id() != userId || User.IsAdmin())
            {
                return Unauthorized();
            }

            var usersProducts = cartService.UsersCart(userId);

            return View(usersProducts);
        }

        [Authorize]
        public IActionResult AddToCart(string productId, string userId)
        {

            if (this.User.Id() != userId || User.IsAdmin())
            {
                return Unauthorized();
            }

            cartService.AddProductToCart(productId, userId);

            TempData[GlobalMessageKey] = "Продуктът беше успешно добавен във вашата количка!";

            return RedirectToAction("All", "Products");
        }

        [Authorize]
        public IActionResult Delete(string productId, string userId)
        {
            cartService.Delete(productId, userId);

            TempData[GlobalMessageKey] = "Продуктът беше успешно премахнат от вашата количка!";

            return RedirectToAction($"MyCart", new { userId = this.User.Id() });
        }
    }
}

SecondHandClothes/Views/Cart/MyCart.cshtml
@model List<CartItemViewServiceModel>

@{
    ViewData["Title"] = "Моята количка";
}

<head>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
    <link href="~/css/DetailsCss.css" rel="stylesheet" />
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>

<div class="container">
    <h1 class="text-center font-weight-bold">@ViewData["Title"]</h1>
    <hr />
    @if (Model.Count() == 0)
    {
        <div class="text-center">
            <hr />
            <h3 class="text-center">Количката ти е празна.</h3>
            <hr />
            <a class="btn btn-primary" role="button" asp-controller="Products" asp-action="All">Пазарувай!</a>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-6">
                @foreach (var product in Model)
                {
                    <div class="card mb-3" style="max-width: 540px;">
                        <div class="row g-0">
                            <div class="col-md-4">
                                <a asp-controller="Products" asp-action="Details" asp-route-id="@product.ProductId" class="card-text btn btn-outline-warning">
                                    <img src=@product.ImageURL class="card-img-top img-responsive rounded-start" alt="Image">
                                </a>
                            </div>
                            <div class="col-md-8 text-center">
                                <div class="card-body">
                                    <h5 class="card-title font-weight-bold">@product.Title</h5>
                                    <hr />
                                    <p class="card-text"><span class="font-weight-bold">Цена: </span>@product.Price</p> 
                                    <hr />
                                </div>
                                <a class="btn btn-danger" role="button" asp-controller="Cart" asp-action="Delete" asp-route-productId=@product.ProductId asp-route-userId=@User.Id()>Премахни от количката!</a>
                            </div>
                        </div>
                    </div>
                }
            </div>
            @{
                var totalSum = Model.Sum(x => (x.Price));
            }
            <div class="col-6">
                <div class="card">
                    <div class="card-body text-center">
                        <h5 class="card-title font-weight-bold">Твоята поръчка:</h5>
                        <hr />
                        @foreach (var product in Model)
                        {
                            <h5>@product.Title - @product.Price лв.</h5>
                            <hr />
                        }
                        <h6 class="card-subtitle mb-2 font-weight-bold ">Общо: @totalSum лв.</h6>
                        <a class="btn btn-primary mt-5" role="button" asp-controller="Orders" asp-action="MakeOrder">Поръчай!</a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>